### ISSUE TITLE
Create the remade .md file for the level0 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#1]
Hey folk's hope u all are doing great!!
If anyone want's to create the readme file  for the level0 then fell free to take this issue ..

**Comment by Roshani9731** [comment]
@Vikash-8090-Yadav Can I work on this?

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav Can I work on this?

Please mention if u r contributor at HSCO22 or not ?

**Comment by khushimarothi** [comment]
Im new to this . So What do  we exactly need to attach in a readme

**Comment by Vikash-8090-Yadav** [comment]
> Im new to this . So What do we exactly need to attach in a readme

Hey @khushimarothi Welcome to the open source journey  :crossed_fingers: . 

**U can  includes the Name of the project's , their brief description , and some screen shot .**
 if possible try to make the Table of content also . 

If u have some other idea about improvement  of the layout of the exsisting project or wana add new one  then feel free to create the issue .. :smile:

**Comment by khushimarothi** [comment]
> > Im new to this . So What do we exactly need to attach in a readme
> 
> Hey @khushimarothi Welcome to the open source journey 🤞 .
> 
> **U can includes the Name of the project's , their brief description , and some screen shot .** if possible try to make the Table of content also .
> 
> If u have some other idea about improvement of the layout of the exsisting project or wana add new one then feel free to create the issue .. 😄

Thank you
