### ISSUE TITLE
Zomato Clone

### ISSUE THREAD

**Issue by royalpinto007** [Vikash-8090-Yadav/Web3.0-World#104]
### Project Description
A Web3 project made using HTML and CSS.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great . But it's not web3 project it;s web2 please correct this . 
Start working on this . 
Thank u  :smile: 

Happy open source
