### ISSUE TITLE
cricket webpage

### ISSUE THREAD

**Issue by targithu** [Vikash-8090-Yadav/Web3.0-World#115]
### Project title
CRICKET WEBPAGE

### Project Description
A WEBSITE WHICH HAS INFORMATION REGARDING CRICKET RECORDS,THE CHAMPIONS IN VARIOUS TOURNAMENTS AND UPCOMING ICC TOURNAMENTS.

### Doc Domain

- [X] Solidity , Html, Css , JavaScript , Web3.js / Ether.js

**Comment by Vikash-8090-Yadav** [comment]
Start working on this . @targithu .
