### ISSUE TITLE
Blog on Soulbound Tokens

### ISSUE THREAD

**Issue by Envoy-VC** [Vikash-8090-Yadav/Web3.0-World#121]
### Project title
What are Soulbound Tokens

### Project Description
In this post, we'll describe SoulBound Tokens (SBTs), which are the fundamental building blocks of the Decentralized Society, a new Web3 trend.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Hacktoberfest 2022, Hacksquad
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@Envoy-VC Great start working on this

**Comment by Envoy-VC** [comment]
hey @Vikash-8090-Yadav I'm done.
