### ISSUE TITLE
Improve ERC-20 ERC-721 ERC-1155 Blog

### ISSUE THREAD

**Issue by Envoy-VC** [Vikash-8090-Yadav/Web3.0-World#123]
### Description of  the change
Enhance the blog by including interactive visuals, detailed use cases for ERC tokens, and a new ERC-777 Standard.

### Domain of Docs

- [x] Readme

#### Are you contributing under any open-source program ?
Hacktoberfest 2022, Hacksquad
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Start working on this .@Envoy-VC

**Comment by Envoy-VC** [comment]
hey @Vikash-8090-Yadav it's done.
