### ISSUE TITLE
Blog on Web3 Glossary

### ISSUE THREAD

**Issue by Envoy-VC** [Vikash-8090-Yadav/Web3.0-World#128]
### Project title
Web3 Glossary

### Project Description
Add a Blog Post on Important terms in web3 and crypto space

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

Hacksquad
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this @Envoy-VC

**Comment by Nitishupkr** [comment]
Can u pls assing me this repo?

**Comment by Envoy-VC** [comment]
@Vikash-8090-Yadav Hey its Done.

**Comment by Vikash-8090-Yadav** [comment]
@Nitishupkr it's already aasigned to @Envoy-VC  u can't work on this
