### ISSUE TITLE
Blog on Smart Contract

### ISSUE THREAD

**Issue by Envoy-VC** [Vikash-8090-Yadav/Web3.0-World#129]
### Project title
Build Your First Smart Contract using Solidity

### Project Description
Step by step guide on making a simple smart contract in solidity using remix ide

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

Hacksquad
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Sure,start working on this @Envoy-VC

**Comment by Envoy-VC** [comment]
@Vikash-8090-Yadav Hey it's done.
