### ISSUE TITLE
Add the Hack club rait logo

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#14]
Hii folk's. 
**In this issue You  are required to make the lable's of  for contributor , repo size , open issue etc as shown below  and Also add the logo of the HACK CLUB RAIT . as shown below after the cover image !**
<br>
![Screenshot from 2022-07-26 23-13-06](https://user-images.githubusercontent.com/85225156/181076922-9abf665b-4a70-4811-ba67-20b4dbe2cf7d.png)

**The logo of the HACK CLUB RAIT IS ATTACHED BELOW** 

![1632670084686-1](https://user-images.githubusercontent.com/85225156/181077201-07455734-42d9-43a1-b7bd-c5b855711afa.jpg)

**PS : Adjust the height and width accordingly .**

**Comment by khushimarothi** [comment]
Can do it👍

**Comment by Vikash-8090-Yadav** [comment]
sure  :smile:
