### ISSUE TITLE
Improve the hacktoberfest image in Readme.md

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#148]
As the image quality is not good , and The image background is also not matching with the readme background .

Goal :

Improve the image , size should be same , should be responsive in desktop as well as in mobile .

please Reply if u want to take this issue .

**Comment by Vikash-8090-Yadav** [comment]
OK sure @jovinkassi . Start working on this .

**Comment by Vikash-8090-Yadav** [comment]
@jovinkassi are u still working on this ?

**Comment by Vikash-8090-Yadav** [comment]
@jovinkassi if u don't reply , i have to give this  to someone . Please reply fast !!

**Comment by chikkibum** [comment]
hey @Vikash-8090-Yadav  Can you assign this issue to me. I think I will be able to contribute to this.

**Comment by Vikash-8090-Yadav** [comment]
@chikkibum sure !

**Comment by chikkibum** [comment]
hey @Vikash-8090-Yadav what would you like me to do exactly?

I have removed the white background from logo file, but do you want me to change hacktoberfest image also, if yes then,how do  you want it ?

![hack](https://user-images.githubusercontent.com/71315985/217014344-e47dc342-d498-4499-82b8-5a9262c821c7.png)

**Comment by Vikash-8090-Yadav** [comment]
can u please share  the ss in discord

**Comment by Vikash-8090-Yadav** [comment]
can u do one thing , just remove the colour background and extract the image with the text only .Let me know this is possible or not .

**Comment by chikkibum** [comment]
hey @Vikash-8090-Yadav yea I have removed background and it would look like this on readme.

![hack](https://user-images.githubusercontent.com/71315985/217023959-c07ce92a-de9a-4118-814c-185d4ed8de4d.png)

**Comment by Vikash-8090-Yadav** [comment]
ya now add this in readme ✌️

**Comment by chikkibum** [comment]
ok

**Comment by chikkibum** [comment]
hey @Vikash-8090-Yadav I still haven't received points under iwoc. can you look into it.

**Comment by Vikash-8090-Yadav** [comment]
> hey @Vikash-8090-Yadav I still haven't received points under iwoc. can you look into it.

ping me in discord

**Comment by jovinkassi** [comment]
I am sorry I couldnt do it due to exams
