### ISSUE TITLE
Write a blog on Polygon Blockchain 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#149]
Hey everyone ,   Polygon blockchain is one of the emerging blockchain coming  nowdays . It take very less transcation fees .......contnue . 

Goal : 
Write about the Polygon  Blockchain , it's use cases and if possible explain  this  with the help   of the images . 

Refrence : 
https://polygon.technology/

**Comment by AnmolSirola** [comment]
I would like to take this issue.

**Comment by Vikash-8090-Yadav** [comment]
Ya sure  , Start working on this ! Don't forget to introduce  yourself to the community
https://github.com/Vikash-8090-Yadav/Web3.0-World/discussions/146
