### ISSUE TITLE
Improve the UI and make this responsiveness

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#152]
Hola contributor  , if anyone want to take this issue make sure that u  have good knowledge of the Frontend tools like CSS , HTML JS , ETC . 

NOTE : Don't try to change the Classes / Id  written in this  file  .  As the classes are linked with the Smart contract directly .

Thank;s .   

Project : https://github.com/Vikash-8090-Yadav/Web3.0-World/tree/main/Level0/New_Voting

**Comment by Durgesh4993** [comment]
I want to work on this may i start working on this

**Comment by daredevil3435** [comment]
I would like to work on this issue. Please assign me this issue

**Comment by Vikash-8090-Yadav** [comment]
@Durgesh4993 are u still working on this ?

**Comment by Durgesh4993** [comment]
yes sir

**Comment by Durgesh4993** [comment]
Sir can i fully change this project

**Comment by Vikash-8090-Yadav** [comment]
yah , but change only images and css . Don't change the classes and id although u can add extra class for css..

**Comment by Durgesh4993** [comment]
Ok sir

**Comment by Durgesh4993** [comment]
## In Desktop - 
![image](https://user-images.githubusercontent.com/98798977/214804692-8a17e909-3e30-4c79-9aec-81e961920b4c.png)

![image](https://user-images.githubusercontent.com/98798977/214804758-62cb86e6-5d9a-472e-b3f3-82dd12e8631d.png)

![image](https://user-images.githubusercontent.com/98798977/214804819-321c8476-c24b-4cae-9c18-799249e95bd5.png)

## In Mobile - 

![image](https://user-images.githubusercontent.com/98798977/214805088-8024e340-298b-43b4-a009-7ae246a78965.png)

![image](https://user-images.githubusercontent.com/98798977/214805146-f2361263-44d9-446e-8c46-dfadf5c30890.png)

![image](https://user-images.githubusercontent.com/98798977/214805216-7e4b1c60-4d15-47ea-b158-7e04bb197581.png)

![image](https://user-images.githubusercontent.com/98798977/214805288-8412f3e3-e9cc-475a-859b-5761b68ae3a9.png)

**Comment by Durgesh4993** [comment]
Hope you liked it can i change any this else the please tell me

**Comment by Durgesh4993** [comment]
If image is not cleared then tell me i will record a vedio of website

**Comment by Vikash-8090-Yadav** [comment]
gr8 , Soon i ll review and give feedback !!

**Comment by Durgesh4993** [comment]
Sir i will send a pr #175 please verify the code

**Comment by Vikash-8090-Yadav** [comment]
Raise the Pr ✌️

**Comment by Durgesh4993** [comment]
I will already raised #175

**Comment by Vikash-8090-Yadav** [comment]
@Durgesh4993 if it's complete  close this issue
