### ISSUE TITLE
Echai Full stack dapp

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Web3.0-World#153]
#### Project Description :
Echai full stack web app using React, ethers.js and hardhat for testing.
   
#### FEATURES: 
A user can donate fund worth of a chai amount to developers(owner) who deployed the site with a message attached to it.
A user can view how many funds the dapp holds.
A user can see whole list of donators from start to latest up to date with their message and funds.

#### Text Stack used:
[x] Solidity
[x] Ethers
[x] React
[x] HardHat
[x] remix

#### Are you contributing under any open source program:
Yes

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this ,. Include this in Level2

**Comment by DevSwayam** [comment]
Thank you !
