### ISSUE TITLE
Readme.md change

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Web3.0-World#154]
### In readme.md the git clone link is not working 
Describe more about the change.

### Domain of Docs

- [x] Readme

#### Screen shots :
1) The white area shows that there is something mis spelled in the white area. and i copy pasted new link from url of browser which is working.
![image](https://user-images.githubusercontent.com/99035115/211210282-55f7c740-afc4-4f2f-9593-735181b9bd9a.png)

2) Same issue with glit clone link.
![image](https://user-images.githubusercontent.com/99035115/211210438-adfb0cd0-4df1-428a-bce2-8cd78edc4891.png)

#### Are you contributing under any open-source program ?
Yes
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Thank's for this .  Start working on this . @DevSwayam
