### ISSUE TITLE
DDrive (Decentralized Drive) using IPFS network.

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Web3.0-World#156]
### Project title
Decentralized Drive System (DDrive)

### Project Description
A Decentralized file strong system in which user can store their files on IPFS network using his meta mask account and user can only access only their files using their own met mask account. All of this uploading and accessing operations will be stored on blockchain using smart contract.
We can also give access of our files other people just like drive with the help of share and owner just have to pass the sharing person public address so that they can access it.

A user can also see and remove hoe many people have access to files.

There are also some complex features which i will include if i am able to.

### Doc Domain

- [x] Solidity.
- [x]  ReactJs
- [x] ethers.js
- [x] Hard Hat
- [x] IPFS

#### Are you contributing under any open-source program ?
yes (SWOC 2023)
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great issue start working on this . Include this   in level2 folder
