### ISSUE TITLE
Balance fetcher 

### ISSUE THREAD

**Issue by monishkajha17** [Vikash-8090-Yadav/Web3.0-World#160]
### Project title
Balance Fetcher

### Project Description
Here the people can see balance of their account by entering their public key

### Doc Domain

- [] Solidity , 
- #### Are you contributing under any open-source program ?
- SWOC

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@monishkajha17 this project consist only of solidity or it's a full stack ?

**Comment by monishkajha17** [comment]
for now only solidity

**Comment by Vikash-8090-Yadav** [comment]
ya then  , Raise an issue  in  Solidity-Pathshala repo .
