### ISSUE TITLE
A decentralized domain name market

### ISSUE THREAD

**Issue by Kaushan-Dutta** [Vikash-8090-Yadav/Web3.0-World#161]
**Project Description**
Building a Dapp where people can buy domain name for their website and after the name is bought they will be rewarded with an NFT which shows that this website belongs to them only

**Problem it Solves**
If the organization who sells the domain names, is not trusted then they can sell the same domain name to other customers and their will be a confusion that who is the real owner of that domain. Here after the domain name is bought it is being directly listed in the blockchain and also the NFT gives a proof that who is the real owner

**Tech Stacks**
- [x] React
- [x] Tailwind
- [x] Hardhat
- [x] Solidity
- [x] Polygon
- [x] Ethers.js

**Comment by Vikash-8090-Yadav** [comment]
gr8 , include this in level2

**Comment by Kaushan-Dutta** [comment]
Ok!! Thanks for accepting
