### ISSUE TITLE
Creating a full stack Crowd Funding App

### ISSUE THREAD

**Issue by Kaushan-Dutta** [Vikash-8090-Yadav/Web3.0-World#180]
### Project title
Crowd Fund

### Project Description
This is going to be a standout project, I am going to work both on frontend and backend technologies. Here the user can create there own campaign with certain description about it and with a target amount. When any contributor visits there website they can chose any number of campaign from the listed ones and can contribute there, at the same time the contributors will get an exclusive nft made on onchain blockchain if they donate more than a cretain amount.

### Tech Stacks
- [x] Solidity
- [x] Hardhat
- [x] Ethers.js
- [x] Web3Modal
- [x] Pinata IPFS 
- [x] Next Js
- [x] Tailwind
- [x] OpenSea
- [x]  Firebase  

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

<hr/>

**Comment by Kaushan-Dutta** [comment]
Also Going to deploy it on Netlify

**Comment by Vikash-8090-Yadav** [comment]
Gr8 ,start working on this !!
