### ISSUE TITLE
Creating a Process of how the project work in Readme file

### ISSUE THREAD

**Issue by Bharadwajshivam28** [Vikash-8090-Yadav/Web3.0-World#182]
It will be good if process of project will be added in Readme file so one can easily understand how the project works

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav If you find it valueable then please assign me this under iwoc with any difficulty tag

**Comment by Vikash-8090-Yadav** [comment]
> It will be good if process of project will be added in Readme file so one can easily understand how the project works 

please elaborate this .

**Comment by Bharadwajshivam28** [comment]
Sir basically my aim is that we should have a process like how is this project working,aim of the project,workflow etc... It will be added in README file so one easily understand the purpose of project , workflow and many other concepts related to the project

**Comment by Vikash-8090-Yadav** [comment]
u want  to create readme instruction for  all the project's ?

**Comment by Bharadwajshivam28** [comment]
> u want  to create readme instruction for  all the project's ?

Yes sir like how the project is running and what is in the project and all and in readme file

**Comment by Vikash-8090-Yadav** [comment]
ok , start working on  this

**Comment by Bharadwajshivam28** [comment]
> ok , start working on  this 

Ok sir sir my aim is to describe all projects in readme and also describe total aim of project

**Comment by Bharadwajshivam28** [comment]
Thanks for this opportunity sir @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
sir i have to describe process of all the projects in web 3.0 world project

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-14 15-48-50](https://user-images.githubusercontent.com/108119109/218707275-b5bfdb16-1919-4606-81ff-df47787552b0.png)
![Screenshot from 2023-02-14 15-49-00](https://user-images.githubusercontent.com/108119109/218707289-681e4492-9e27-4b91-899c-59b114280f5e.png)

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-14 15-48-50](https://user-images.githubusercontent.com/108119109/218707369-aadda792-6252-4022-a0e1-2404aaabc10d.png)

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav Sir bascially there are 2 files which contains projects .

So can i describe each project one by one what is the project and aim of project with some photographs

**Comment by Bharadwajshivam28** [comment]
One by one describing each project  and at last will descibe the total Web3.0 World project .Whole aim of this project @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
Can i go on with my idea

**Comment by Vikash-8090-Yadav** [comment]
> Can i go on with my idea

ya sure , go with this idea . And feel free to ask if u stuck at nay point !!

**Comment by Vikash-8090-Yadav** [comment]
@Bharadwajshivam28 don't create the readme for the frontend project as per now !! go with the level 0,1,2 .

**Comment by Bharadwajshivam28** [comment]
ok sir @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
sir each project readme will be seprate or in one readme that exist in repo

**Comment by Bharadwajshivam28** [comment]
> > Can i go on with my idea
> 
> ya sure , go with this idea . And feel free to ask if u stuck at nay point !!
ok sir

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-14 17-51-09](https://user-images.githubusercontent.com/108119109/218737530-5d7c0f77-9f10-46ae-8ff6-3b7e10713444.png)
![Screenshot from 2023-02-14 17-51-22](https://user-images.githubusercontent.com/108119109/218737543-8cf80c7b-f55b-4bb3-bcf5-3929155b7246.png)
![Screenshot from 2023-02-14 17-51-31](https://user-images.githubusercontent.com/108119109/218737551-2f073461-a532-47a2-93bc-4fcd2f1bdb4d.png)

**Comment by Bharadwajshivam28** [comment]
These are the projects in each level so the process and description  of these will be added in the one Readme file or seprate

**Comment by Vikash-8090-Yadav** [comment]
For each level there is already readme file present ,check level 0 for better understanding, create same  for level 1 and level 2 .Hope u get the point .

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
sir can the images be used  like

**Comment by Bharadwajshivam28** [comment]
and stylish fonts and emoji ?

**Comment by Bharadwajshivam28** [comment]
sir for 0 it is created but can i make o also good more with better explanation

**Comment by Vikash-8090-Yadav** [comment]
> and stylish fonts and emoji ?

ya . go for it

**Comment by Vikash-8090-Yadav** [comment]
> sir for 0 it is created but can i make o also good more with better explanation

yup , update the things . then i ll review and merge it .

**Comment by Bharadwajshivam28** [comment]
ok sir i will also add describing the projects with images and all

**Comment by Bharadwajshivam28** [comment]
Thanks sir working on it
