### ISSUE TITLE
Writing Documentation of Project in HIndi Language

### ISSUE THREAD

**Issue by Bharadwajshivam28** [Vikash-8090-Yadav/Web3.0-World#183]
Hello Respected sir
   If you like my idea then we can write a Documentation on this project in Hindi Language

Aim of writing Document of Project in  Hindi Language is that Many people understand Hindi language well so one can read the documentation in Hindi language and understand Project well

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav  If you find it valueable then please assign me this under iwoc with any difficulty tag

**Comment by Vikash-8090-Yadav** [comment]
> Hello Respected sir
>    If you like my idea then we can write a Documentation on this project in Hindi Language
> 
> Aim of writing Document of Project in  Hindi Language is that Many people understand Hindi language well so one can read the documentation in Hindi language and understand Project well

i ll think upon it . Let u know soon !!

**Comment by Bharadwajshivam28** [comment]
ok sir @Vikash-8090-Yadav
