### ISSUE TITLE
Write blog about how to add smart contracts on GitHub

### ISSUE THREAD

**Issue by daredevil3435** [Vikash-8090-Yadav/Web3.0-World#184]
I'll write blog about how developer can upload his/her smart contracts on GitHub directly from Remix IDE.

**Comment by daredevil3435** [comment]
@Vikash-8090-Yadav sir can you confirm if I could do this?

**Comment by Vikash-8090-Yadav** [comment]
@daredevil3435 ya sure , start working on this  ,

**Comment by daredevil3435** [comment]
Thank you sir

**Comment by GitWiz01** [comment]
@daredevil3435 Are you still working on it ?

**Comment by daredevil3435** [comment]
yes

**Comment by daredevil3435** [comment]
I'll be submitting it by today

**Comment by GitWiz01** [comment]
@daredevil3435 Ok buddy
