### ISSUE TITLE
Add SWOC image in readme 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#186]
Add this image in the  readme file , where al the open source event images placed .
![swoc](https://user-images.githubusercontent.com/85225156/218995949-52fdecef-a2d6-4884-a1ed-6483e601f27d.png)

**Comment by Bharadwajshivam28** [comment]
assign this to me sir @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
Sir i have done the task by adding image so please assign issue to me for i do pr

**Comment by Bharadwajshivam28** [comment]
close it sir @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav ise close kro sir
