### ISSUE TITLE
Add kwoc image

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#187]
Add this image in the readme file , where al the open source event images placed .

Write the kwoc'23  on the image , before attaching .

![kharagpur winter of code](https://user-images.githubusercontent.com/85225156/218996341-9f0a399d-a6b1-4bd0-8438-6995a3f9d3e5.png)

**Comment by Bharadwajshivam28** [comment]
assign this to me sir @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
close it sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav
