### ISSUE TITLE
iwoc logo

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#188]
Add this image in the readme file , where al the open source event images placed .
![iwoc_logo](https://user-images.githubusercontent.com/85225156/218998600-b5817d71-6e3c-4fa8-a677-ea72d43d1ffb.png)

**Comment by Bharadwajshivam28** [comment]
assign this to me sir @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
Sir i have done the task by adding issue please assign so i can pr it

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav sir can i do the pr in one

**Comment by Bharadwajshivam28** [comment]
i have added images of there so can i make one single pr for three

**Comment by Vikash-8090-Yadav** [comment]
> i have added images of there so can i make one single pr for three

if possible try to make diff branches for this

**Comment by Bharadwajshivam28** [comment]
ok sir doing it

**Comment by anime-sh-github** [comment]
Hi @Vikash-8090-Yadav
Plz assign this issue to me.

**Comment by anime-sh-github** [comment]
Sir, I have added the image.

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav close it sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav close it sir

**Comment by Vikash-8090-Yadav** [comment]
u can also close  by yourself . please do that

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
sir point nai milega

**Comment by Bharadwajshivam28** [comment]
ap hi close krdo sir

**Comment by Bharadwajshivam28** [comment]
apke main repo m 2 issue h wo dono ko

**Comment by Vikash-8090-Yadav** [comment]
issue no ?

**Comment by Bharadwajshivam28** [comment]
bata rha

**Comment by Bharadwajshivam28** [comment]
#188
