### ISSUE TITLE
Improving Readme.md

### ISSUE THREAD

**Issue by A91y** [Vikash-8090-Yadav/Web3.0-World#195]
### Description of  the change
Mistakes found in README.md

### Domain of Docs

- [x] Readme
- [ ] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [ ] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [ ] Solidity , Python3 , Web3.py
- [ ] Other , feel free to mention below

#### Are you contributing under any open-source program ?
IWOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
what mistakes did u encountered with?

**Comment by A91y** [comment]
![IMG_20230217_184923.jpg](https://user-images.githubusercontent.com/65825207/219663748-74f65ccc-d6f8-4842-ba1d-2aba250c29b3.jpg)

![Screenshot_2023-02-17-18-50-52-13_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/65825207/219663749-d0d50516-b9e4-4e45-985f-decbe49574f9.jpg)

These are the few mistakes that can be solved to make it more prettier.

**Comment by suyashmadhesia** [comment]
Is this issue is fixed ? @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
start working on this @A91y
