### ISSUE TITLE
improving index.html of SendtoEther

### ISSUE THREAD

**Issue by GitWiz01** [Vikash-8090-Yadav/Web3.0-World#198]
### Description of  the change
improving index.html of SendtoEther

### Domain of Docs

- [] Html
- [] css
- [] js

#### Are you contributing under any open-source program ?
        
IWOC'23 

<hr/>

**Comment by GitWiz01** [comment]
![issue1](https://user-images.githubusercontent.com/123467623/219963725-1a795e8b-a03a-4faf-b2d4-0d949785a4f9.png)

@Vikash-8090-Yadav  I want to correct these mistakes. please assign me this issue and add iwoc and difficulty level tag sir.
Hope to contribute soon 😊

**Comment by Vikash-8090-Yadav** [comment]
yah @GitWiz01   start working  on this . don't change the classes and id altough u can add your wn classes  as these classes is linked with the web3 .

**Comment by GitWiz01** [comment]
thank you @Vikash-8090-Yadav

**Comment by GitWiz01** [comment]
@Vikash-8090-Yadav please Close the issue sir.
