### ISSUE TITLE
Adding readme.md file in level 0 and correct all the grammatical errors.

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Web3.0-World#20]
### Description of  the change
The readme.md files inside folder level 0 ( sendtoEather0 ) is empty I want to fix it and fix all the existing grammatical errors (inside all the folders).

### Domain of Docs

- [x] Readme
- [x] Documentation
#### Are you contributing under any open-source program ?
SSOC'22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great issue start working on it @AnmolSirola
