### ISSUE TITLE
change folder name 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#22]
Hello folk's hope u all are doing well
If anyone want's to take this issue feel free to comment

**Task : change the name of docs to .docs present in the root directory** 

Thank u :smile:

**Comment by tanya-gupta25** [comment]
I want to work on this issue under hsoc

**Comment by Vikash-8090-Yadav** [comment]
> I want to work on this issue under hsoc
Please mention the  open source programme in which u r contributing ...

**Comment by Vikash-8090-Yadav** [comment]
> I want to work on this issue under hsoc

Ok great start working on it ...
