### ISSUE TITLE
Cover image  is not working in mobile version 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#26]
### Description of  the change
Hey all if any one want to take's this issue feel free to comment . 
**Task : The cover image is not showing in the mobile version . .**

### Domain of Docs

- [x] Readme

Describe more about the change.

![IMG_20220806_124627](https://user-images.githubusercontent.com/85225156/183238990-236edaf4-62bd-4303-bc82-aab2da1be592.jpg)

**Comment by GundaSudarrshan** [comment]
@Vikash-8090-Yadav  Can You Assign me this Issue

**Comment by Vikash-8090-Yadav** [comment]
ya sure.....

**Comment by GundaSudarrshan** [comment]
i have a doubt so if i add width inside the image tag i think problem will be solved

**Comment by Vikash-8090-Yadav** [comment]
@GundaSudarrshan  are u from HSOC or SSOC ?

**Comment by Vikash-8090-Yadav** [comment]
> i have a doubt so if i add width inside the image tag i think problem will be solved

ya , u can try this also

**Comment by GundaSudarrshan** [comment]
@Vikash-8090-Yadav  yeah i have raised the PR pls review

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav  yeah i have raised the PR pls review 

Ya .i will update u  by EOD

**Comment by GundaSudarrshan** [comment]
> @GundaSudarrshan are u from HSOC or SSOC ?

HSOC @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
Ok got it..

**Comment by Vikash-8090-Yadav** [comment]
Hwy @GundaSudarrshan the image still not working on mobile version .Just do one thing just drag and drop that image in the placw of previous one...

**Comment by GundaSudarrshan** [comment]
> Hwy @GundaSudarrshan the image still not working on mobile version .Just do one thing just drag and drop that image in the placw of previous one...

I didn't get it , sorry can you say again

**Comment by Vikash-8090-Yadav** [comment]
I am saying that  the image which u r inserted from the image folder instead of taking through the image folder just drag and drop that image in place of that .... Let me know if this clear or not ?

@GundaSudarrshan

**Comment by GundaSudarrshan** [comment]
yeah I have updated it please Check
