### ISSUE TITLE
hello world smart contract 

### ISSUE THREAD

**Issue by srinjoy-26** [Vikash-8090-Yadav/Web3.0-World#3]
A hello world smart contract in solidity.

**Comment by Vikash-8090-Yadav** [comment]
> A hello world smart contract in solidity.

Hey this look's great ! Please mention the directory in which u want to add this code  file .Then i will assign this issue to u  .
Happy learning ✌️

**Comment by srinjoy-26** [comment]
> > A hello world smart contract in solidity.
> 
> Hey this look's great ! Please mention the directory in which u want to add this code file .Then i will assign this issue to u . Happy learning ✌️

In the contracts folder present in the truff directory

**Comment by Vikash-8090-Yadav** [comment]
> > > A hello world smart contract in solidity.
> > 
> > Hey this look's great ! Please mention the directory in which u want to add this code file .Then i will assign this issue to u . Happy learning ✌️
> 
> Web3.0-World/Level2/MetaNft_Minting/Truff/contracts

Nope u can't do like this .U have to make ur own file for hello world and create ur own truffle structure.Iin this way u will destroy the working of the MetaNft_Minting.

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Is someone still working on this hello world contract ??

**Comment by Vikash-8090-Yadav** [comment]
@srinjoy-26 are u still working on this issue 
 ?

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola u can work on  this now if u want...

**Comment by AnmolSirola** [comment]
Okay Sir I will work on it . I just want to ask that I have to only create a smart contract inside remix or in my own ide with truffle/ganache.

**Comment by Vikash-8090-Yadav** [comment]
yes you have to work  on your ide with the Ganache , truffle and make frontend with the smart contract ...

**Comment by AnmolSirola** [comment]
Okay Sir will do it but I need some time

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  any update ?

**Comment by AnmolSirola** [comment]
Sir, I wont be able to do it because my end sems are going on right now .

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola any updates ?

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Forgot about this issue also working on twitter dapp wont be able to complete this one

**Comment by Vikash-8090-Yadav** [comment]
Close this then @Vikash-8090-Yadav

**Comment by srinjoy-26** [comment]
@Vikash-8090-Yadav I guess this issue was cursed , that's why no one completed it
