### ISSUE TITLE
level 1 readme

### ISSUE THREAD

**Issue by deepshikha2708** [Vikash-8090-Yadav/Web3.0-World#35]
### Description of  the change
Writing into the readme file of level 1

### Domain of Docs

- [x] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by deepshikha2708** [comment]
@Vikash-8090-Yadav will you please assign me this issue? and please also tell what exactly needs to be added in level 1?

**Comment by Vikash-8090-Yadav** [comment]
@deepshikha2708 Are you contributing under any open-source program ?

**Comment by Vikash-8090-Yadav** [comment]
@deepshikha2708  ??

**Comment by deepshikha2708** [comment]
yes in HSOC22

**Comment by Vikash-8090-Yadav** [comment]
can you please share the SS of the mistake u r seeing in the README
Thank u ...
