### ISSUE TITLE
Improve the UI of the level0 projects > Web3.0-World/Level0/SendToEather/

### ISSUE THREAD

**Issue by iamifechi** [Vikash-8090-Yadav/Web3.0-World#37]
Improve the frontend part of the level0 projects > SendToEather

**Comment by iamifechi** [comment]
Can I work on this?

**Comment by ankur0904** [comment]
Can I work on this issue?

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904 ya sure please tell the project name on which u wana to work ..

**Comment by ankur0904** [comment]
Web3.0-World/Level0/SendToEather/

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  start working on this

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  . any updates ?

**Comment by ankur0904** [comment]
Merged successfully
https://github.com/Vikash-8090-Yadav/Web3.0-World/pull/55

**Comment by ankur0904** [comment]
Please check it.
