### ISSUE TITLE
Image for Web3.O.World

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#4]
## If anyone want to create the Image for the Web3.O.world then feel free to comment . 

**The sample for the image is shown below :** 

![Screenshot from 2022-07-24 19-05-12](https://user-images.githubusercontent.com/85225156/180649700-dab58445-c3c9-4276-9a32-c3864fa40aff.png)

# **The original image should not be  exactly same as shown above . The image should  have blockchain , web3 related pics ..**

**Comment by GundaSudarrshan** [comment]
@Vikash-8090-Yadav  can you pls assign me this issue

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav can you pls assign me this issue

Sure !
