### ISSUE TITLE
[README] adding gitpod link and correcting the step 8 of staging commits

### ISSUE THREAD

**Issue by chirag0002** [Vikash-8090-Yadav/Web3.0-World#40]
### Description of  the change
- The Gitpod link should be there on the README to configure the repository on the browser without worrying about dependencies and forking of the repo.
- Step 8 of README must be corrected as it says to stage the commits by command `git add .`, it is a wrong open-source practice. Instead, you have to stage the commits only the files or folder you have worked upon.

### Domain of Docs

- [] Readme

#### Are you contributing under any open-source program?

Yes, under SSOC.

<hr/>

**Comment by chirag0002** [comment]
@Vikash-8090-Yadav assign me this issue, I want to work on this.

**Comment by Vikash-8090-Yadav** [comment]
Greate idea @chirag0002  start working on this ..
