### ISSUE TITLE
Add SSOC LOGO

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#41]
Hey folk's hop u  all are doing well in this  issue  you all have to attach the SSOC logo just after t the HSOC 
The  logo  is given below adjust the height and width accordingly . 
Thank u 
![IMG-20220820-WA0008](https://user-images.githubusercontent.com/85225156/185743071-147dd0ec-99fb-4413-8fd6-3494a8792b83.jpg)

**Comment by chirag0002** [comment]
@Vikash-8090-Yadav are you talking about, adding the SSOC logo in the README.md file?
If yes, I want to work on this issue.

**Comment by Vikash-8090-Yadav** [comment]
Yes @chirag0002  . OK 
Start working  on this issue...
