### ISSUE TITLE
How to start blockchain

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#45]
If anyone wants to create  the blog on the the topic "How to start blockchain "  from zero to advanced level 

**Made image folder if u r using any image under the blog section.**

f anyone want's take this issue feel free to comment . Below are the points need to keep in mind while writing blog

1.     Introduction
2.     Pre requesite
3.     Main content
4.     Flow diagram
5.     Conclusion
6.     Refrence

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I would like to work on this project .

**Comment by Vikash-8090-Yadav** [comment]
sure @AnmolSirola

**Comment by manisha-nair28** [comment]
@Vikash-8090-Yadav Can we write more articles on blockchain-related topics in the Blog section?

**Comment by Vikash-8090-Yadav** [comment]
Yes @manisha-nair28  u can create a seprate issue for this .

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I wanted to ask I have to write about how to start blockchain development or like how to blockchain works ?

**Comment by Vikash-8090-Yadav** [comment]
You have to give the roadmap  "How beginenr can start blockchain" @AnmolSirola
