### ISSUE TITLE
Add more project 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#46]
If anyone intersted to take this issue .. Comment on this 
.
Task : You have to add some project in the Project_ideas section . 
Thank u :smile:

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I am only supposed to give some ideas right? in the Project_ideas section ?

**Comment by Vikash-8090-Yadav** [comment]
Ya add that project  in the format ..give the name of the project ,status , description etc  @AnmolSirola

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I would like to work on this issue

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola Raise an issue for that project idea .

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola create a new issue for your project  and link that issue no with the P.R u  opened ,

**Comment by Vikash-8090-Yadav** [comment]
Along with tell how many project idea are u adding so that i can attach the  label a/c to that

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Okay Sir

**Comment by Vikash-8090-Yadav** [comment]
Create a new  issue and link  that issue no with the P.R u opened as u linked this issue with that p.r if i  merge  that pr then this issue will also closed that's y i am saying .this

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Yes sir I got your point but I am asking when I create a new issue  for new projects . I am supposed to add only new projects in the list or should I keep the old projects list and add new projects to it.

**Comment by Vikash-8090-Yadav** [comment]
Ok i guess u r not getting . so let it be same , Just tell me how many project u want to added or u added in the project idea directory ?

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I have added 9 projects right now will add few more till tomorrow morning .I will let you know when I am done adding.
