### ISSUE TITLE
Staking Dapp on Ploygon testnet

### ISSUE THREAD

**Issue by nirban256** [Vikash-8090-Yadav/Web3.0-World#50]
### Project title
Matic Staking Dapp

### Project Description
It is a Matic Token Staking dapp where user will be able to stake matic tokens for 1 month, 3 months, 6 months and will gain interest based on there amount staked.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Social Summer Of Code 2022
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
include this in Level1 folder .

**Comment by nirban256** [comment]
ok
