### ISSUE TITLE
 Create the contributing.md for this repo

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#51]
As this file is already present in the directory with the name : contributing.md
I reuest if anyone want to take thiis then please comment .

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I would like to work on this issue .

**Comment by Vikash-8090-Yadav** [comment]
Ok @AnmolSirola start working on this

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav What all things should I add inside it
