### ISSUE TITLE
NFT-Market-Place

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Web3.0-World#53]
### Project title
NFT-Market-Place

### Project Description
An NFT-MarketPlace where you can list and sell your nft , and we will use IPFS to store our data.

### Doc Domain

- [x] Solidity , ReactJs ,Ether.js , Hardhat, IPFS

#### Are you contributing under any open-source program ?
SSOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great idea @AnmolSirola please tell the folder structure

**Comment by AnmolSirola** [comment]
I will be adding this project in level2 folder
