### ISSUE TITLE
Create Issue temaplate 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#6]
Greetings of the day folks !!
If anyone want's to create the issue template then feel free to comment 

The issue template should contains ->  **Bug report , Feature request  and  other .**  
like shown below 

![Screenshot from 2022-07-25 17-32-13](https://user-images.githubusercontent.com/85225156/180773864-fc8bfbc3-6875-4518-9309-30cbb57b4be3.png)

**Comment by surjyaneeh** [comment]
@Vikash-8090-Yadav Can You assign it to me?
And I have doubt about where should I include that issue_template.md file.

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav Can You assign it to me? And I have doubt about where should I include that issue_template.md file.

Yeah sure !

create **.github/ISSUE_TEMPLATE/add-project.md , custom.md , imporevements.md**

and this  folder should be in the root directory only .

**Comment by surjyaneeh** [comment]
> > @Vikash-8090-Yadav Can You assign it to me? And I have doubt about where should I include that issue_template.md file.
> 
> Yeah sure !
> 
> create **.github/ISSUE_TEMPLATE/add-project.md , custom.md , imporevements.md**
> 
> and this folder should be in the root directory only .

Can you suggest me the contents of custom.md file?

**Comment by Vikash-8090-Yadav** [comment]
> > > @Vikash-8090-Yadav Can You assign it to me? And I have doubt about where should I include that issue_template.md file.
> > 
> > 
> > Yeah sure !
> > create **.github/ISSUE_TEMPLATE/add-project.md , custom.md , imporevements.md**
> > and this folder should be in the root directory only .
> 
> Can you suggest me the contents of custom.md file?
sure , 

![Screenshot from 2022-07-27 19-37-08](https://user-images.githubusercontent.com/85225156/181269670-d8598524-df00-4d4c-90b1-8b854a7a0feb.png)
