### ISSUE TITLE
Web3-Todo-Application

### ISSUE THREAD

**Issue by nirban256** [Vikash-8090-Yadav/Web3.0-World#63]
### Project title
Web3 Todo App

### Project Description
It is a todo list application which the user can change according to there daily task performed

### Doc Domain

- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
include this in level 1

**Comment by nirban256** [comment]
ok

**Comment by nirban256** [comment]
@Vikash-8090-Yadav can I close the issue?

**Comment by Vikash-8090-Yadav** [comment]
sure @nirban256
