### ISSUE TITLE
Improve UI for send to ether 

### ISSUE THREAD

**Issue by kunal232i** [Vikash-8090-Yadav/Web3.0-World#67]
### Description of  the change
Improve UI of [SendToEther](https://github.com/kunal232i/Web3.0-World/tree/main/Level0/SendToEther) file

### Domain of Docs

- [] Readme
- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, in hacktoberfest.
<hr/>

**Comment by kunal232i** [comment]
can you assign this to me..?

**Comment by Vikash-8090-Yadav** [comment]
ya sure @kunal232i

**Comment by Durgesh4993** [comment]
Sir can you assign this work to me

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i are u still working on this ??

**Comment by kunal232i** [comment]
> @kunal232i are u still working on this ??

currently, I'm not able to work on this project due to some reasons. you can assign it to @Durgesh4993

**Comment by Durgesh4993** [comment]
ok thank you bro,  @Vikash-8090-Yadav now can i start working on this project of Social winter of code

**Comment by Vikash-8090-Yadav** [comment]
Ya if u are doing under Swoc , Please pr after 1st jan .

**Comment by Durgesh4993** [comment]
ok sir

**Comment by Vikash-8090-Yadav** [comment]
@Durgesh4993 start working on this issue. 
Thing's to kept in mind  while changing UI :
1. Don't ever change the classes  and id name as  they are totally linked with the smart contract (Backened) 
2. U can add classes after the class but don't chnange the exist one .

**Comment by Durgesh4993** [comment]
ok sir i will remeber

**Comment by Durgesh4993** [comment]
![image](https://user-images.githubusercontent.com/98798977/213142617-f395ec30-cb7d-4728-bd94-5607195a7128.png)

**Comment by Durgesh4993** [comment]
Sir, its look like that hope you like that if you want to suggest me any changes please tell me

**Comment by Vikash-8090-Yadav** [comment]
Yah , gr8 . raise a pr for this . Also look in readme if required  change the readme also  .

**Comment by Durgesh4993** [comment]
sir, please tell if there are any issue in this code  if not please merge the pull request #163 and #164

**Comment by Vikash-8090-Yadav** [comment]
Why u make two pr for the same project 🙄

**Comment by Durgesh4993** [comment]
i am totally unable to send in one pr, i don't know what is the issue i will try to many times but its't be possible then i try secperate html or css file.

**Comment by Vikash-8090-Yadav** [comment]
okh, wait

**Comment by Durgesh4993** [comment]
Thank you for merge the PR any other work for me sir
