### ISSUE TITLE
I want to improve the files in Web3.0-World/Level0/Voting/

### ISSUE THREAD

**Issue by ankur0904** [Vikash-8090-Yadav/Web3.0-World#68]
### Description of  the change
Describe more about the change.

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Start working on this @ankur0904

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904 are u still working on this ?

**Comment by ankur0904** [comment]
No sir.

**Comment by daredevil3435** [comment]
can I work on this?

**Comment by Vikash-8090-Yadav** [comment]
@daredevil3435 can u please check the other  project as the level0 voting is upto the date
