### ISSUE TITLE
Create P.R template 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Web3.0-World#7]
Greetings of the day folks !!
If anyone want's to create the issue template then feel free to comment
The template should look like this shown below

![Screenshot from 2022-07-25 18-06-45](https://user-images.githubusercontent.com/85225156/180780114-598771cb-08ef-4167-a798-555fc0dbd12f.png)

**Comment by GundaSudarrshan** [comment]
@Vikash-8090-Yadav  Can You assign it to me
and i have doubt where should i include that pr_template.md file
should i keep in main folder or create a separate folder for that or what??

**Comment by Vikash-8090-Yadav** [comment]
Yeah sure !
 **make the two folder that is docs/pull-request_template.md

and .github/pull-request_template.md** 
amd these folder should be in the root directory only . 

**for more details u can go through the official docs of the github..**
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

Feel free to ask anything , anytime ! :smile:
