### ISSUE TITLE
Add project ideas

### ISSUE THREAD

**Issue by akshat-jn-crypto** [Vikash-8090-Yadav/Web3.0-World#70]
### Description of  the change
Describe more about the change.

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by akshat-jn-crypto** [comment]
please assign this issue to me

**Comment by Vikash-8090-Yadav** [comment]
what u want  to do ? please decsribe your work ?

**Comment by akshat-jn-crypto** [comment]
Add detailed articles on topics like
Decentralized Blog
Building your own blog doesn't only improve your coding skill, but your online presence too. If you have a blog and share content regularly, you can get a lot of visitors which can increase your online presence.

You can use this opportunity to build your blog on any blockchain.

Checkout Nader's article on how to build a full-stack blog application with Next.js and Solidity on Polygon blockchain https://blog.suhailkakar.com/13-projects-you-can-do-to-become-a-web3-and-blockchain-master-beginner-to-expert

**Comment by Vikash-8090-Yadav** [comment]
i gues for the hacktoberfest don't do this  this may    spam and can exclude my repo . Better  if  u made changes in the  code . 
Hope u understand @akshat-jn-crypto
