### ISSUE TITLE
Add Marketplace  site 

### ISSUE THREAD

**Issue by Omega12Pirme** [Vikash-8090-Yadav/Web3.0-World#73]
Hlo, i want to add the marketplace file in levle1 folder . this consist of the Adding the fruits  with the id name , cost and   name of  the fruits . then the added can be shown below. 
After Adding anyone can buy the fruits of their  choice and also can view.

Please assign this issue to me . so  that i can contribute . 
I am contributing under the Hackktoberfest 2022 .

**Comment by Vikash-8090-Yadav** [comment]
@Omega12Pirme Great idea start working on this .

**Comment by Omega12Pirme** [comment]
@Vikash-8090-Yadav  please this issue to me so that i can work on this . 
Thanks in advance

**Comment by Vikash-8090-Yadav** [comment]
Sure  @Omega12Pirme
