### ISSUE TITLE
Full site to get Data feed ETH/USD via chainlink 

### ISSUE THREAD

**Issue by Omega12Pirme** [Vikash-8090-Yadav/Web3.0-World#79]
Hii sir , please assign this issue to me ,
In this i want create a smart contract which can get the real time data feeds with the help of the chainLink API .

This  contains the full site with the working . 

The folder structure is ; Level1/Chainlink/RealTimedata.sol

**Comment by Vikash-8090-Yadav** [comment]
HII @Omega12Pirme . This looks very great and nice idea . Start working on this
