### ISSUE TITLE
Blog on erc20 and erc721 and rc 1155 . 

### ISSUE THREAD

**Issue by Omega12Pirme** [Vikash-8090-Yadav/Web3.0-World#84]
Hey , please assign this issue to me . I want to add   the  blog's on the topic Erc and erc21

**Comment by Omega12Pirme** [comment]
Great start working on this issue  .

**Comment by Vikash-8090-Yadav** [comment]
Great idaea. Please follow the l guidelines  of the  blog

**Comment by Omega12Pirme** [comment]
Updated  the issue  please check and assign this to me .
